### ISSUE TITLE
Have a problem... Plz Help)

### ISSUE THREAD

**Issue by Cosmat** [BetaRavener/upy-websocket-server#10]
WebREPL daemon started on ws://0.0.0.0:8266
Started webrepl in normal mode
scandone
state: 0 -> 2 (b0)
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "ws_connection.py", line 2, in <module>
ImportError: no module named 'websocket'

**Comment by BohemianHacks** [comment]
in ws_connection.py
change:
`from websocket import websocket`

to:
`from uwebsocket import websocket`
